"""fix

Revision ID: 0c1e736167ba
Revises: 52cf9d82ec9f
Create Date: 2022-05-15 00:11:15.919106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1e736167ba'
down_revision = '52cf9d82ec9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SENSOR_VALUE', 'sensor_value_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SENSOR_VALUE', sa.Column('sensor_value_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
