"""empty message

Revision ID: 60e0e830ce7a
Revises: 67d013604912
Create Date: 2022-05-15 20:34:01.620734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e0e830ce7a'
down_revision = '67d013604912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TOOL', sa.Column('node', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TOOL', 'node')
    # ### end Alembic commands ###
