"""empty message

Revision ID: 67d013604912
Revises: 
Create Date: 2022-05-15 20:26:44.227296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d013604912'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SENSOR_VALUE',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('sensor_value_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['SENSOR.sensor_id'], ),
    sa.PrimaryKeyConstraint('sensor_id', 'sensor_value_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SENSOR_VALUE')
    # ### end Alembic commands ###
